//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIDSS.Reports.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.56\\V4;Initial Catalog=eidss_v4_Ivan;Persist Security Info=" +
            "True;User ID=sa;Password=btrp!2010")]
        public string eidss_v4_IvanConnectionString {
            get {
                return ((string)(this["eidss_v4_IvanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=EIDSS_v4;Integrated Security=True")]
        public string EIDSS_v4ConnectionString {
            get {
                return ((string)(this["EIDSS_v4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=EIDSS_v4_AZ_65k;Integrated Security=True")]
        public string EIDSS_v4_40KConnectionString {
            get {
                return ((string)(this["EIDSS_v4_40KConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=EIDSS_v4_AZ;Integrated Security=True")]
        public string EIDSS_v4_AZConnectionString {
            get {
                return ((string)(this["EIDSS_v4_AZConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IVANPC;Initial Catalog=eidss_v5;Integrated Security=True")]
        public string eidss_v5ConnectionString {
            get {
                return ((string)(this["eidss_v5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IVANPC;Initial Catalog=EIDSS_v5_GAT;Integrated Security=True")]
        public string EIDSS_v5_GATConnectionString {
            get {
                return ((string)(this["EIDSS_v5_GATConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=EIDSS_v5_AZ_65k;Integrated Security=True")]
        public string EIDSS_v5_AZ_65kConnectionString {
            get {
                return ((string)(this["EIDSS_v5_AZ_65kConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GORODENTSEVAT;Initial Catalog=eidss_v6;Integrated Security=True")]
        public string eidss_v6ConnectionString1 {
            get {
                return ((string)(this["eidss_v6ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=eidss_v6;Integrated Security=True")]
        public string eidss_v6ConnectionString {
            get {
                return ((string)(this["eidss_v6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ivanpc;Initial Catalog=EIDSS_v6_IQ;Integrated Security=True")]
        public string EIDSS_v6_IQConnectionString {
            get {
                return ((string)(this["EIDSS_v6_IQConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=FALCON;Integrated Security=True")]
        public string FALCON_ConnectionString {
            get {
                return ((string)(this["FALCON_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZURINM\\SQL2008;Initial Catalog=eidss_v6;Integrated Security=True")]
        public string eidss_v6ConnectionString2 {
            get {
                return ((string)(this["eidss_v6ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VDOVIN\\SQL2008;Initial Catalog=EIDSS_TH;Integrated Security=True")]
        public string eidss_v6ConnectionString3 {
            get {
                return ((string)(this["eidss_v6ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MIKE-PC\\ZURIN;Initial Catalog=eidss_v6;Integrated Security=True")]
        public string eidss_v6ConnectionString4 {
            get {
                return ((string)(this["eidss_v6ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VDOVIN\\SQL2008;Initial Catalog=EIDSS_KZ;Integrated Security=True")]
        public string eidss_v6ConnectionStringKZ {
            get {
                return ((string)(this["eidss_v6ConnectionStringKZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.255.34.106\\ngsql08Dev1;Initial Catalog=EIDSS_TH;Persist Security " +
            "Info=True;User ID=srvcEIDSSTH;Password=nBZD66)")]
        public string EIDSS_THConnectionString {
            get {
                return ((string)(this["EIDSS_THConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-FDQHCBK\\EIDSS;Initial Catalog=AZDB_MIK;Integrated Security=Tr" +
            "ue")]
        public string AZDB_MIKConnectionString {
            get {
                return ((string)(this["AZDB_MIKConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=INTEL-PC\\EIDSSDB;Initial Catalog=UA_ADB;Integrated Security=True")]
        public string UA_ADBConnectionString {
            get {
                return ((string)(this["UA_ADBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=INTEL-PC\\EIDSSDB;Initial Catalog=EIDSS_KZ;Integrated Security=True")]
        public string EIDSS_KZConnectionString {
            get {
                return ((string)(this["EIDSS_KZConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MAX-PALAMARCHUK;Initial Catalog=EIDSS_KZ;Integrated Security=True")]
        public string eidss_MP {
            get {
                return ((string)(this["eidss_MP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=INTEL-PC\\EIDSSDB;Initial Catalog=AZ_DB;Integrated Security=True")]
        public string INTEL_AZ_DBConnectionString {
            get {
                return ((string)(this["INTEL_AZ_DBConnectionString"]));
            }
        }
    }
}
