'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyConfiguration("Release"), _
 Assembly: AssemblyCompany("Black & Veatch Special Projects Corp."), _
 Assembly: AssemblyTitle("BV framework"), _
 Assembly: AssemblyProduct("BV framework"), _
 Assembly: AssemblyCopyright("Copyright © 2005-2021, Black & Veatch Special Projects Corp."), _
 Assembly: AssemblyTrademark("Trademark by Black & Veatch Special Projects Corp."), _
 Assembly: AssemblyVersion("6.1.0.90"), _
 Assembly: AssemblyFileVersion("6.1.0.88")> 

